name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Lint
        run: pnpm lint
        env:
          FORCE_COLOR: 2
      - name: Build
        run: pnpm build
        env:
          FORCE_COLOR: 2
      - name: Check size
        uses: getsentry/size-limit-action@v5
        with:
          main_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: build
